#include <iostream>
#include "saturating_counter.hpp"
#include "branch_history_table_entry.hpp"
#include "branch_history_register.hpp"
#include "trace_file_parser.hpp"
using namespace std;

int main() 
{
	saturating_counter counter(strong_nottaken);
    cout << "Hello, World!" << endl;
	cout << "Current counter prediction is: " << counter.isTaken() << " which is " << counter.getCounterStatusString()<< endl;
	counter.updateTaken();
	cout << "Current counter prediction is: " << counter.isTaken() << " which is " << counter.getCounterStatusString()<< endl;
	counter.updateTaken();
	cout << "Current counter prediction is: " << counter.isTaken() << " which is " << counter.getCounterStatusString()<< endl;
	counter.updateTaken();
	cout << "Current counter prediction is: " << counter.isTaken() << " which is " << counter.getCounterStatusString()<< endl;
	counter.updateTaken();
	cout << "Current counter prediction is: " << counter.isTaken() << " which is " << counter.getCounterStatusString()<< endl;
	counter.updateTaken();
	cout << "Current counter prediction is: " << counter.isTaken() << " which is " << counter.getCounterStatusString()<< endl;
	counter.updateNotTaken();
	cout << "Current counter prediction is: " << counter.isTaken() << " which is " << counter.getCounterStatusString()<< endl;
	counter.updateNotTaken();
	cout << "Current counter prediction is: " << counter.isTaken() << " which is " << counter.getCounterStatusString()<< endl;
	counter.updateTaken();
	cout << "Current counter prediction is: " << counter.isTaken() << " which is " << counter.getCounterStatusString()<< endl;
	counter.updateNotTaken();
	cout << "Current counter prediction is: " << counter.isTaken() << " which is " << counter.getCounterStatusString()<< endl;
	counter.updateNotTaken();
	cout << "Current counter prediction is: " << counter.isTaken() << " which is " << counter.getCounterStatusString()<< endl;
	
	branch_history_register bhr(7);
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateNotTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateNotTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateNotTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateNotTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateNotTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateNotTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateNotTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateNotTaken();
	cout << "Binary: " << bhr.getBinaryString() << " | Value: " << bhr.getLongValue() << endl;
	bhr.updateNotTaken();
	
	trace_file_parser tracefile("tracetest.in");
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	tracefile.getNextEntry();
	cout << "Current Entry is: "<< tracefile.getCurrentTraceEntryString() << " | filestatus: " << tracefile.isTraceFileGood() << endl;
	
	branch_history_table_entry bht_entry_test;
	cout <<"0 | " << bht_entry_test.getEntryStringDecimal() << " |" << endl;
	bht_entry_test.updateTaken();
	bht_entry_test.isTakenAutoReplace(0);
	cout <<"0 | " << bht_entry_test.getEntryStringDecimal() << " |" << endl;
	bht_entry_test.updateTaken();
	bht_entry_test.isTakenAutoReplace(0);
	cout <<"0 | " << bht_entry_test.getEntryStringDecimal() << " |" << endl;
	bht_entry_test.updateTaken();
	bht_entry_test.isTakenAutoReplace(0);
	cout <<"0 | " << bht_entry_test.getEntryStringDecimal() << " |" << endl;
	bht_entry_test.updateTaken();
	bht_entry_test.isTakenAutoReplace(0);
	cout <<"0 | " << bht_entry_test.getEntryStringDecimal() << " |" << endl;
	bht_entry_test.updateNotTaken();
	bht_entry_test.isTakenAutoReplace(0);
	cout <<"0 | " << bht_entry_test.getEntryStringDecimal() << " |" << endl;
	bht_entry_test.updateNotTaken();
	bht_entry_test.isTakenAutoReplace(0);
	cout <<"0 | " << bht_entry_test.getEntryStringDecimal() << " |" << endl;
	bht_entry_test.updateTaken();
	bht_entry_test.isTakenAutoReplace(0);
	cout <<"0 | " << bht_entry_test.getEntryStringDecimal() << " |" << endl;
	bht_entry_test.updateTaken();
	bht_entry_test.isTakenAutoReplace(1000);
	cout <<"0 | " << bht_entry_test.getEntryStringDecimal() << " |" << endl;
	bht_entry_test.updateTaken();
	bht_entry_test.isTakenAutoReplace(1000);
	cout <<"0 | " << bht_entry_test.getEntryStringDecimal() << " |" << endl;
	bht_entry_test.updateTaken();
	bht_entry_test.isTakenAutoReplace(1000);
	cout <<"0 | " << bht_entry_test.getEntryStringDecimal() << " |" << endl;
	bht_entry_test.updateTaken();
	bht_entry_test.isTakenAutoReplace(20000);
	cout <<"0 | " << bht_entry_test.getEntryStringDecimal() << " |" << endl;
	
	
	//cout << "Something is " << newsomething.getSum();
    return 0;
}